version: '3.3'

services:

  dev:
    build: .
    ports:
      - "5000:5000"
    command: python -m flask run
    volumes:
      - ./:/app/

  test:
    network_mode: "host"
    build: .
    command: python -m unittest discover -s ./warehouse -p *_test.py
    depends_on:
      - dev