version: '3.3'

services:

  dev:
    build: .
    ports:
      - "5000:5000"
    command: python -m flask run
    volumes:
      - ./:/app/

  test:
    network_mode: "host"
    build: .
    command: python -m unittest discover -s ./warehouse -p *_test.py
    depends_on:
      - dev

  eventstore:
    image: eventstore/eventstore:20.10.2-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"