version: '3.3'

services:

  test:
    build: .
    command: python -m unittest discover -s ./warehouse -p *_test.py

  dev:
    build: .
    ports:
      - "5000:5000"
    command: python -m flask run
    volumes:
      - ./:/app/